version: 0.2

phases:
  install:
    commands:
      - npm install --production
artifacts:
  files:
    - app.js
    - node_modules/**/*
    - routes/**/*
    - bin/**/*
    - package.json
    - .ebextensions/**/*